/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controller.c_Filme;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AlterarFilme extends javax.swing.JInternalFrame {

    DefaultTableModel tabela;

    public AlterarFilme() {
        initComponents();
        tabela = new DefaultTableModel();
        tabela.addColumn("id");
        tabela.addColumn("Nome");
        tabela.addColumn("Genero");
        tabela.addColumn("Ano");
        tabela.addColumn("Assistido");
        tb_filme.setModel(tabela);
        pesquisar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_limpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_filme = new javax.swing.JTable();
        tf_genero = new javax.swing.JTextField();
        tf_id = new javax.swing.JTextField();
        cb_assistido = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        bt_salvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_ano = new javax.swing.JTextField();
        bt_deletar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Alterar Filme");
        setPreferredSize(new java.awt.Dimension(700, 500));

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        tb_filme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_filme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_filmeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_filme);

        tf_id.setEnabled(false);
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        cb_assistido.setText("Assistido");
        cb_assistido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_assistidoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome:");

        jLabel5.setText("Gênero:");

        jLabel3.setText("Ano:");

        tf_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_anoActionPerformed(evt);
            }
        });

        bt_deletar.setText("Deletar");
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nome)
                    .addComponent(tf_genero)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(bt_deletar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_limpar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_salvar)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(tf_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(cb_assistido)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_assistido))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_salvar)
                            .addComponent(bt_limpar)
                            .addComponent(bt_deletar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed

        tf_nome.setText("");
        tf_genero.setText("");
        tf_ano.setText("");
        cb_assistido.setSelected(false);
        bt_salvar.setEnabled(true);
    }//GEN-LAST:event_bt_limparActionPerformed

    private void cb_assistidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_assistidoActionPerformed

    }//GEN-LAST:event_cb_assistidoActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        int id = Integer.parseInt(tf_id.getText());
        String nome = tf_nome.getText();
        String genero = tf_genero.getText();
        int ano = Integer.parseInt(tf_ano.getText());
        int assistido = 0;

        if (cb_assistido.isSelected()) {
            assistido = 1;
        }

        c_Filme.Editar(id, nome, genero, ano, assistido);
        JOptionPane.showMessageDialog(null, "Editado com sucesso");
        bt_salvar.setEnabled(false);
        limparTabela();
        pesquisar();
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void tf_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_anoActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void tb_filmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_filmeMouseClicked
        bt_deletar.setEnabled(true);
        bt_limpar.setEnabled(true);
        bt_salvar.setEnabled(true);

        int linha = tb_filme.getSelectedRow();

        tf_id.setText((String) (tabela.getValueAt(linha, 0)));
        tf_nome.setText((String) tabela.getValueAt(linha, 1));
        tf_genero.setText((String) tabela.getValueAt(linha, 2));
        tf_ano.setText((String) tabela.getValueAt(linha, 3));
        cb_assistido.setSelected((Boolean) tabela.getValueAt(linha, 4));
    }//GEN-LAST:event_tb_filmeMouseClicked

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed
        c_Filme.Deletar(Integer.parseInt(tf_id.getText()));
        JOptionPane.showMessageDialog(null, "Deletado com sucesso.");
        limparTabela();
        tf_nome.setText("");
        tf_genero.setText("");
        tf_ano.setText("");
        cb_assistido.setSelected(false);
        pesquisar();
    }//GEN-LAST:event_bt_deletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_deletar;
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JCheckBox cb_assistido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_filme;
    private javax.swing.JTextField tf_ano;
    private javax.swing.JTextField tf_genero;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nome;
    // End of variables declaration//GEN-END:variables

    public void pesquisar() {
        String dados[][] = c_Filme.Pesquisar().clone();
        for (int i = 0; i < dados.length; i++) {
            tabela.addRow(new String[]{dados[i][0], dados[i][1], dados[i][2], dados[i][3], dados[i][4]});
        }
    }

    public void limparTabela() {
        for (int i = tabela.getRowCount() - 1; i >= 0; i--) {
            tabela.removeRow(i);
        }
    }

}
