/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controller.c_Serie;
import javax.swing.table.DefaultTableModel;


public class ExibirSeries extends javax.swing.JInternalFrame {

    DefaultTableModel tabela;
    
    public ExibirSeries() {
        initComponents();
        
        tabela = new DefaultTableModel();
        tabela.addColumn("id");
        tabela.addColumn("Nome");
        tabela.addColumn("Genero");
        tabela.addColumn("Ano");
        tabela.addColumn("Assistido");
        tb_exibirseries.setModel(tabela);
        pesquisar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tb_exibirseries = new javax.swing.JTable();

        setClosable(true);
        setTitle("Exibir Séries");
        setPreferredSize(new java.awt.Dimension(640, 480));

        tb_exibirseries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb_exibirseries);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_exibirseries;
    // End of variables declaration//GEN-END:variables

     public void pesquisar() {
        String dados[][] = c_Serie.Pesquisar().clone();
        for (int i = 0; i < dados.length; i++) {
            tabela.addRow(new String[]{dados[i][0], dados[i][1], dados[i][2], dados[i][3], dados[i][4]});
        }
    }

}
