/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controller.c_Filme;
import javax.swing.table.DefaultTableModel;

public class ExibirFilmes extends javax.swing.JInternalFrame {

    DefaultTableModel tabela;

    public ExibirFilmes() {
        initComponents();
        tabela = new DefaultTableModel();
        tabela.addColumn("id");
        tabela.addColumn("Nome");
        tabela.addColumn("Genero");
        tabela.addColumn("Ano");
        tabela.addColumn("Assistido");
        tb_exibirfilmes.setModel(tabela);
        pesquisar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_exibirfilmes = new javax.swing.JTable();

        setClosable(true);
        setTitle("Exibir Filmes");
        setPreferredSize(new java.awt.Dimension(640, 480));

        tb_exibirfilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_exibirfilmes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_exibirfilmes;
    // End of variables declaration//GEN-END:variables

    public void pesquisar() {
        String dados[][] = c_Filme.Pesquisar().clone();
        for (int i = 0; i < dados.length; i++) {
            tabela.addRow(new String[]{dados[i][0], dados[i][1], dados[i][2], dados[i][3], dados[i][4]});
        }
    }

}
