/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controller.c_Filme;
import java.awt.Image;
import javax.swing.JOptionPane;

/**
 *
 * @author 55859
 */
public class NovoFilme extends javax.swing.JInternalFrame {

    int assistido;

    public NovoFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_genero = new javax.swing.JTextField();
        cb_assistido = new javax.swing.JCheckBox();
        bt_salvarnovofilme = new javax.swing.JButton();
        bt_limpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_ano = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Novo Filme");

        jLabel1.setText("Nome:");

        jLabel2.setText("Gênero:");

        cb_assistido.setText("Assistido");
        cb_assistido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_assistidoActionPerformed(evt);
            }
        });

        bt_salvarnovofilme.setText("Salvar");
        bt_salvarnovofilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarnovofilmeActionPerformed(evt);
            }
        });

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        jLabel3.setText("Ano:");

        tf_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_anoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_salvarnovofilme))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(tf_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tf_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(cb_assistido))
                        .addComponent(tf_genero)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_assistido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salvarnovofilme)
                    .addComponent(bt_limpar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed

        tf_nome.setText("");
        tf_genero.setText("");
        tf_ano.setText("");
        cb_assistido.setSelected(false);

        bt_salvarnovofilme.setEnabled(true);

    }//GEN-LAST:event_bt_limparActionPerformed

    private void tf_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_anoActionPerformed

    private void cb_assistidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_assistidoActionPerformed
    }//GEN-LAST:event_cb_assistidoActionPerformed

    private void bt_salvarnovofilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarnovofilmeActionPerformed

        String nome = tf_nome.getText();
        String genero = tf_genero.getText();
        int ano = Integer.parseInt(tf_ano.getText());
        assistido = 0;
        
        if (cb_assistido.isSelected()) {
            assistido = 1;
        }

        c_Filme.Salvar(nome, genero, ano, assistido);
        JOptionPane.showMessageDialog(null, "Salvo com sucesso");

        bt_salvarnovofilme.setEnabled(false);

    }//GEN-LAST:event_bt_salvarnovofilmeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton bt_salvarnovofilme;
    private javax.swing.JCheckBox cb_assistido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tf_ano;
    private javax.swing.JTextField tf_genero;
    private javax.swing.JTextField tf_nome;
    // End of variables declaration//GEN-END:variables

    private void setIconImage(Image image) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
