package Telas;

import Controller.c_Serie;
import javax.swing.JOptionPane;

public class NovoSerie extends javax.swing.JInternalFrame {

    int assistido;

    public NovoSerie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_genero = new javax.swing.JTextField();
        cb_assistido = new javax.swing.JCheckBox();
        bt_salvarnovoserie = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_temporadas = new javax.swing.JTextField();
        bt_limpar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Nova Série");

        cb_assistido.setText("Assistido");
        cb_assistido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_assistidoActionPerformed(evt);
            }
        });

        bt_salvarnovoserie.setText("Salvar");
        bt_salvarnovoserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarnovoserieActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Gênero:");

        jLabel3.setText("Temporadas:");

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_salvarnovoserie))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_nome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_genero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(tf_temporadas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(cb_assistido))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_temporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_assistido))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salvarnovoserie)
                    .addComponent(bt_limpar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed

        tf_nome.setText("");
        tf_genero.setText("");
        tf_temporadas.setText("");
        cb_assistido.setSelected(false);
        bt_salvarnovoserie.setEnabled(true);

    }//GEN-LAST:event_bt_limparActionPerformed

    private void bt_salvarnovoserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarnovoserieActionPerformed

        String nome = tf_nome.getText();
        String genero = tf_genero.getText();
        int temporadas = Integer.parseInt(tf_temporadas.getText());
        int assistido = 0;

        if (cb_assistido.isSelected()) {
            assistido = 1;
        }

        c_Serie.Salvar(nome, genero, temporadas, assistido);
        JOptionPane.showMessageDialog(null, "Salvo com sucesso");

        bt_salvarnovoserie.setEnabled(false);
    }//GEN-LAST:event_bt_salvarnovoserieActionPerformed

    private void cb_assistidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_assistidoActionPerformed

        assistido = 0;
    }//GEN-LAST:event_cb_assistidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton bt_salvarnovoserie;
    private javax.swing.JCheckBox cb_assistido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tf_genero;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_temporadas;
    // End of variables declaration//GEN-END:variables
}
