package Telas;

import Controller.c_Filme;
import Controller.c_Serie;
import javax.swing.table.DefaultTableModel;

public class PesquisarTodos extends javax.swing.JInternalFrame {

    DefaultTableModel tabela;

    public PesquisarTodos() {
        initComponents();
        tabela = new DefaultTableModel();
        tabela.addColumn("id");
        tabela.addColumn("Nome");
        tabela.addColumn("Genero");
        tabela.addColumn("Ano");
        tabela.addColumn("Temporadas");
        tabela.addColumn("Assistido");
        tb_pesquisa.setModel(tabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pesquisa = new javax.swing.JTable();
        cb_escolha = new javax.swing.JComboBox<>();
        tf_pesquisa = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pesquisar");

        tb_pesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_pesquisa);

        cb_escolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filme", "Série" }));
        cb_escolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_escolhaActionPerformed(evt);
            }
        });

        tf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisaActionPerformed(evt);
            }
        });

        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_pesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_pesquisar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_escolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_escolhaActionPerformed


    }//GEN-LAST:event_cb_escolhaActionPerformed

    private void tf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pesquisaActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed

        limparTabela();
        if (cb_escolha.getSelectedItem().equals("Filme")) {
            String dados[][] = c_Filme.Pesquisar(tf_pesquisa.getText()).clone();
            for (int i = 0; i < dados.length; i++) {
                tabela.addRow(new String[]{dados[i][0], dados[i][1], dados[i][2], dados[i][3], "", dados[i][4]});
            }
        } else {
            String dados[][] = c_Serie.Pesquisar(tf_pesquisa.getText()).clone();
            for (int i = 0; i < dados.length; i++) {
                tabela.addRow(new String[]{dados[i][0], dados[i][1], dados[i][2], "", dados[i][3], dados[i][4]});
            }
        }
    }//GEN-LAST:event_bt_pesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JComboBox<String> cb_escolha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_pesquisa;
    private javax.swing.JTextField tf_pesquisa;
    // End of variables declaration//GEN-END:variables

    public void pesquisar() {
        pesquisarFilme();
        pesquisarSerie();
    }

    public void pesquisarFilme() {
        String dados[][] = c_Filme.Pesquisar().clone();
        for (int i = 0; i < dados.length; i++) {
            tabela.addRow(new String[]{dados[i][0], dados[i][1], dados[i][2], dados[i][3], "", dados[i][4]});
        }
    }

    public void pesquisarSerie() {
        String dados[][] = c_Serie.Pesquisar().clone();
        for (int i = 0; i < dados.length; i++) {
            tabela.addRow(new String[]{dados[i][0], dados[i][1], dados[i][2], "", dados[i][3], dados[i][4]});
        }
    }

    public void limparTabela() {
        for (int i = tabela.getRowCount() - 1; i >= 0; i--) {
            tabela.removeRow(i);
        }
    }
}
